# Generated by Django 3.2 on 2023-09-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jewelry',
            options={'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
    ]
