# Generated by Django 4.2.5 on 2023-09-16 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0002_alter_jewelry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jewelry',
            options={},
        ),
    ]
