# Generated by Django 4.2.5 on 2023-09-19 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0003_alter_jewelry_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewelry',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
