# Generated by Django 4.2.5 on 2023-09-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0005_stripepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='amount',
            field=models.IntegerField(max_length=10000000),
        ),
    ]
