# Generated by Django 4.2.5 on 2023-09-19 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0006_alter_stripepayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepayment',
            name='address_city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='address_country',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
