# Generated by Django 4.2.5 on 2023-09-19 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0007_stripepayment_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
