export const productActionTypes = {
  GET_PRODUCT: 'GET_PRODUCT',
  GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE',

  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
  GET_ALL_PRODUCT_COPY: 'GET_ALL_PRODUCT_COPY',

  SET_SEARCH: 'SET_SEARCH',
  SET_CATEGORY: 'SET_CATEGORY'
};
